
package net.strocamp.wildfly.tests.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PingImplService", targetNamespace = "http://jaxws.tests.wildfly.strocamp.net/", wsdlLocation = "http://192.168.56.20:8080/jaxws-tests-0.0.1-SNAPSHOT/PingImpl?wsdl")
public class PingImplService
    extends Service
{

    private final static URL PINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PINGIMPLSERVICE_EXCEPTION;
    private final static QName PINGIMPLSERVICE_QNAME = new QName("http://jaxws.tests.wildfly.strocamp.net/", "PingImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.56.20:8080/jaxws-tests-0.0.1-SNAPSHOT/PingImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PINGIMPLSERVICE_WSDL_LOCATION = url;
        PINGIMPLSERVICE_EXCEPTION = e;
    }

    public PingImplService() {
        super(__getWsdlLocation(), PINGIMPLSERVICE_QNAME);
    }

    public PingImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PINGIMPLSERVICE_QNAME, features);
    }

    public PingImplService(URL wsdlLocation) {
        super(wsdlLocation, PINGIMPLSERVICE_QNAME);
    }

    public PingImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PINGIMPLSERVICE_QNAME, features);
    }

    public PingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ping
     */
    @WebEndpoint(name = "PingImplPort")
    public Ping getPingImplPort() {
        return super.getPort(new QName("http://jaxws.tests.wildfly.strocamp.net/", "PingImplPort"), Ping.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ping
     */
    @WebEndpoint(name = "PingImplPort")
    public Ping getPingImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.tests.wildfly.strocamp.net/", "PingImplPort"), Ping.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PINGIMPLSERVICE_EXCEPTION!= null) {
            throw PINGIMPLSERVICE_EXCEPTION;
        }
        return PINGIMPLSERVICE_WSDL_LOCATION;
    }

}
